### ISSUE TITLE
Limit the number of spent CP's to the value of the card

### ISSUE THREAD

**Issue by BasqueMex** [bga-his/bga-hereistand#1]
Move action is allowing to do infinite actions. I'd suggest a harder check: if you have 0 CP's to spend, don't show the options, just pass to next player. If you have 1 CP to spend, show only options that are 1 CP or cheaper (recruit merc/cav, recruit corsary, translate, move, assault, ...), etc

**Comment by ristonj** [comment]
We no longer show options you can't afford. I think we'll need a longer term fix (i.e. a dictionary that lists actions and their costs), but for now this is done.
